### PR TITLE
Add BSL 1.1 license

### PR DESCRIPTION
**Pull request by vinzvinci**
#### Description of the change\*

As requested, we will use the BSL 1.1 license for our project.

CC @KukretiShubham @shuklaritvik06 

CLOSES #ISSUENO 

N/A

#### Checklist\*

**Please make sure you have done the following:**

- [x] 😄 I've read [CONTRIBUTING.md][contributing] and my PR is up to standards.
- [ ] 🎨 The changes in this PR meet the design plan.
- [ ] 🐛 I've tested my PR's source changes for any bugs/render issues.
- [ ] 🧪 I've worked through build failures and tests are passing.
- [x] 📄 I've updated the necessary documentation changes.

#### Notes

[contributing]: https://github.com/web3community/DEV-NFT/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by shuklaritvik06 — APPROVED** [review]
Looks Good to me , Let's wait for shubham :)

**Review by krishguptadev — APPROVED** [review]

**Review by KukretiShubham — APPROVED** [review]
LGTM
What @mkubdev says

**Review by mkubdev — COMMENTED** [review]
Ok for BSL1.1

**Review by mkubdev — APPROVED** [review]
LGTM 👌🏻

**Comment by shuklaritvik06** [comment]
> Congrats on merging your first pull request! Welcome to the community tada

he is the founder bot 😅  😂

**Pull request merged**
