### PR TITLE
fix: user canno't access creation without login

### PR DESCRIPTION
**Pull request by mkubdev**
#### Description of the change

fix: user canno't access the marketplace if not logged to github. We redirect the user to the `/login` page

### CODE REVIEW

**Review by krishguptadev — APPROVED** [review]

**Comment by KukretiShubham** [comment]
Why? we should allow a user if they just came to buy the NFT. Then they can visit marketplace without loggin in with GitHub. Just they won't be able to mint it. To mint they will have to login later, that they can do from the dashboard itself.

**Comment by shuklaritvik06** [comment]
> 

+1

**Comment by shuklaritvik06** [comment]
> Why? we should allow a user if they just came to buy the NFT. Then they can visit marketplace without loggin in with GitHub. Just they won't be able to mint it. To mint they will have to login later, that they can do from the dashboard itself.

+1

**Comment by mkubdev** [comment]
Oh. I though that the user wont see the marketplace if he isn't connected. I fix

**Review by krishguptadev — APPROVED** [review]

**Comment by KukretiShubham** [comment]
Tobe fixed with next PR

**Pull request merged**
